config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import (MaterialCreateView, MaterialListView,
                             MaterialDetailView,
                             MaterialUpdateView, MaterialDeleteView, published)
app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MaterialDeleteView.as_view(), name='delete'),
    path('published/<int:pk>', published, name='published'),
]

users/urls.py
from users.apps import UsersConfig
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import UserCreateView, email_verification, NewPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password/', NewPasswordView.as_view(), name='reset_password'),
]

materials/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(verbose_name='содержимое')
    img = models.ImageField(upload_to='materials/',
                            verbose_name='изображение', **NULLABLE)
    date_creation = models.DateTimeField(verbose_name='дата создания',
                                         **NULLABLE)
    is_published = models.BooleanField(default=True,
                                       verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    slug = models.CharField(max_length=150, verbose_name='слаг', **NULLABLE)


class Meta:
    verbose_name = 'статья'
    verbose_name_plural = 'статьи'

    def __str__(self):
        return self.title

materials/views.py
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (CreateView, ListView, DetailView,
                                  UpdateView, DeleteView)

from materials.models import Material


class MaterialCreateView(CreateView):
    model = Material
    fields = ('title', 'body', 'is_published', 'img', 'date_creation')
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_material = form.save()
            new_material.slug = slugify(new_material.title)
            new_material.save()

        return super().form_valid(form)


class MaterialUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body')
#   success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_material = form.save()
            new_material.slug = slugify(new_material.title)
            new_material.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter()
        return queryset


class MaterialDetailView(DetailView):
    model = Material

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MaterialDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('materials:list')


def published(request, pk):
    item = get_object_or_404(Material, pk=pk)
    if item.is_published:
        item.is_published = False
    else:
        item.is_published = True

    item.save()

    return redirect(reverse('materials:list'))

materials/templates/materials/material_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p> Хотите удалить статью {{ object.title }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                    Подтвердить
                            </button>
                            <a href="{% url 'materials:list' %}" class="btn btn-warning"> Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="card-header">
            <h3 class="card-title">
                 Материал "{{ object.title }}" ({{ object.slug}})
            </h3>
        </div>
        <!--убираем цикл тк работаем с CBV-->
        <div class="col-md-4 mb-4">
          <img src="{% mediapath object.image %}" class="card-img-top" />
          <div class="card-body text-center">
                <p>{{ object.body }}</p>
          </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
        </div>
    </div>

</div><!-- /.container -->
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                    </button>
                    <button type="submit">
                     <a href="{% url 'materials:list'%}"> Назад </a>
                        </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

materials/templates/materials/material_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
  <a class="btn btn-outline-primary" href="{% url 'materials:create' %}">Добавить материал</a>
</div>

<div class="container">
    <div class="row text-start">
        {% for object in object_list %}
      <div class="col-lg-4 mb-3">
        <div style="width: 240px; height: 240px; overflow: hidden;">
          <img src="{% mediapath object.image %}" style="width: 100%; height: auto;" />
        </div>
        <h2 class="fw-normal">{{ object|title }}</h2>

        <div class="btn-group mb-3">
          <a href="{% url 'materials:view' object.pk %}"
             class="btn btn-sm btn-outline-secondary">View</a>
          <a href="{% url 'materials:edit' object.pk %}"
             class="btn btn-sm btn-outline-secondary">Edit</a>
          <a href="{% url 'materials:delete' object.pk %}"
             class="btn btn-sm btn-outline-danger">Delete</a>
        </div>
        {% if object.is_published %}
        <a class="btn btn-warning" href="{% url 'materials:published' object.pk %}">Не публиковать</a>
        {% else %}
        <a class="btn btn-success"  href="{% url 'materials:published' object.pk %}">Опубликовать</a>
        {% endif %}

      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}