catalog/urls.py
from django.urls import path
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView
from catalog.apps import CatalogConfig
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('<int:pk>/product/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from users.apps import UsersConfig
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import UserCreateView, email_verification, NewPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password/', NewPasswordView.as_view(), name='reset_password'),
]

catalog/models.py
from django.db import models
from datetime import datetime
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.category_name}'

    class Meta():
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    product_name = models.CharField(max_length=50, verbose_name='наименование')
    desc = models.TextField(verbose_name='описание',
                            **NULLABLE)
    image = models.ImageField(upload_to='products/',
                              verbose_name='превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='categories',
                                 verbose_name='категория')
    quantity_per_unit = models.PositiveIntegerField(verbose_name='цена за шт.', default='0')
    creation_date = models.DateField(verbose_name='дата создания', default=datetime.now)
    last_change_date = models.DateTimeField(verbose_name='дата последнего изменения', default=datetime.now,
                                            **NULLABLE)

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    owner = models.ForeignKey(User, verbose_name='владелец', **NULLABLE, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.category} {self.product_name} '

    class Meta():
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('can_change_is_published', 'Can change is_published'),
            ('can_change_desc', 'Can change description'),
            ('can_change_category', 'Can change category')
        ]


class Version(models.Model):
    name = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="product",
        verbose_name="Наименование"
    )
    version_number = models.PositiveIntegerField(
        verbose_name="номер версии"
    )
    version_name = models.CharField(
        max_length=100,
        verbose_name="наименование версии"
    )
    current_version = models.BooleanField(
        default=False,
        verbose_name="Признак текущей версии"
    )

    def __str__(self):
        return f"{self.name} {self.version_number} {self.version_name}"

    class Meta:
        verbose_name = "Версия продукта"
        verbose_name_plural = "Версии продуктов"

catalog/forms.py
from catalog.models import Product, Version
from django.forms import ModelForm, BooleanField, ValidationError


class StyleFormMixin(object):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    BLACKLIST = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
                 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ('views_count', 'slug', 'owner')

    def clean_product_name(self):
        cleaned_data = self.cleaned_data["product_name"]
        for word in self.BLACKLIST:
            if word in cleaned_data.lower():
                raise ValidationError(f'Наименование не должно содержать слово {word}')
        return cleaned_data

    def clean_desc(self):
        cleaned_data = self.cleaned_data["desc"]
        for word in self.BLACKLIST:
            if word in cleaned_data.lower():
                raise ValidationError(f'Описание не должно содержать слово {word}')
        return cleaned_data


class ProductModeratorForm(StyleFormMixin, ModelForm):
    BLACKLIST = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
                 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('desc', 'category', 'is_published')

    def clean_desc(self):
        cleaned_data = self.cleaned_data["desc"]
        for word in self.BLACKLIST:
            if word in cleaned_data.lower():
                raise ValidationError(f'Описание не должно содержать слово {word}')
        return cleaned_data


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from catalog.models import Product, Version
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from pytils.translit import slugify
from django.forms import inlineformset_factory, modelform_factory
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied


class ProductListView(ListView):
    model = Product

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter()
        return queryset


# def home(request):
#     product_list = Product.objects.all()
#     context = {
#         'object_list': product_list,
#         'title': 'Главная'
#     }
#     return render(request, 'catalog/material_list.html', context)


class ProductDetailView(DetailView, LoginRequiredMixin):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.views_count += 1
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["version"] = Version.objects.filter(name=self.object, current_version=True)
        return context_data


# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(id=pk),
#         'title': f'{product_item.product_name}'
#     }
#     return render(request, 'catalog/product_detail.html', context)


def contacts(request):
    context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contacts.html', context)


class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = modelform_factory(Product, form=ProductForm, exclude=['last_change_date', 'views_count', 'slug'])

    def form_valid(self, form):
        if form.is_valid():
            new_material = form.save()
            user = self.request.user
            new_material.owner = user
            new_material.slug = slugify(new_material.product_name)
            new_material.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Формирование формсета
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def get_success_url(self):
        return reverse('catalog:home')


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    @transaction.atomic
    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        product_versions = Version.objects.all()
        active_v_counter = 0
        if formset.is_valid():
            self.object = form.save()
            self.object.slug = slugify(self.object.product_name)
            formset.instance = self.object
            formset.save()

        for product in product_versions:
            if product.name_id == self.object.id and product.current_version:
                active_v_counter += 1

        try:
            if active_v_counter > 1:
                raise
        except active_v_counter > 1:
            pass
        finally:
            if active_v_counter < 2:
                return super().form_valid(form)
            else:
                transaction.set_rollback(True)
                form.add_error(None, 'У продукта не может быть более одной активной версии.')
                return self.form_invalid(form)

    def get_success_url(self):
        return reverse('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Формирование формсета
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('product.can_change_is_published') and user.has_perm(
                'product.can_change_desc') and user.has_perm('product.can_change_category'):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {{title}}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
 {% include 'catalog/includes/inc_catalog_menu.html'%}

    {% block content %}
    {% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y'%}</small>
            </div>
        </div>
    </footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<h1 class="display-4">Контакты</h1>
</div>

<div class="container">
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p> Хотите удалить статью {{ object.product_name }} ?</p>
                            <button type="submit" class="btn btn-outline-danger">
                                    Подтвердить
                            </button>
                            <a href="{% url 'catalog:home'%}"> Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container py-4">
    <div class="row justify-content-center">
        <!--убираем цикл тк работаем с CBV-->
        <div class="col-md-4 mb-4">
            <img src="{% mediapath object.image %}" class="card-img-top"/>
            <div class="card-body text-center">
                <h5 class="card-title">{{ object.product_name|title }} ({{ object.slug }})</h5>
                <p class="card-text"><strong>{{ object.quantity_per_unit }} руб.</strong></p>
                <p class="card-text">Категория: {{ object.category }}</p>
                <p class="card-text">Описание: {{ object.desc }}</p>
                <p class="card-text">Версия:
                    {% for object in version %}
                    {{ object.version_number }} {{object.version_name }}
                    {% endfor %}</p>

                <p class="card-text">Создан: {{ object.creation_date }}</p>
                <p class="card-text">Количество просмотров: {{ object.views_count }}</p>
            </div>
        </div>
    </div>

</div><!-- /.container -->
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">>
        <div class="row">
            <div class="col-6">
                <div class="card">

                    {% if not object %}
                    <div class="card-header">
                        <h4 class="card-title">Создание продукта</h4>
                    </div>
                    {% else %}
                    <div class="card-header">
                        <h4 class="card-title">Изменение продукта</h4>
                    </div>
                    {% endif %}

                    <div class="card body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                        <button type="submit">
                            <a href="{% url 'catalog:home' %}"> Назад </a>
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Версия продукта</h4>
                    </div>
                    <div class="card body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить материал</a>
    {% endif %}
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Товары</h1>
</div>

<div class="container">
    <div class="row text-start">

        {% for object in object_list %}
        <div class="col-lg-4 mb-3">
            <div style="width: 240px; height: 240px; overflow: hidden;">
                <img src="{% mediapath object.image %}" style="width: 100%; height: auto;"/>
            </div>

            <h2 class="fw-normal">{{ object.product_name|title }}</h2>
            <p>{{ object.desc|slice:":100" }}</p>
            <p><h6><strong>{{ object.quantity_per_unit }} руб.</strong></h6></p>

            <div class="btn-group mb-3">
                <a href="{% url 'catalog:product_detail' object.pk %}"
                   class="btn btn-sm btn-outline-secondary">View</a>

                {% if perms.product.can_change_is_published and perms.product.can_change_desc and perms.product.can_change_category or user == product.owner %}
                <a href="{% url 'catalog:update_product' object.pk %}"
                   class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'catalog:delete_product' object.pk %}"
                   class="btn btn-sm btn-outline-danger">Delete</a>
                {% endif %}

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}